version: '3.6'

services:
  peatio:
    image: "${PEATIO_IMAGE}"
    depends_on:
      - proxy
      - db
      - redis
      - rabbitmq
    env_file:
      - ../config/peatio.env
    ports:
      - "167.99.168.129:8000:8000"
    domainname: peatio.freeriding.us
    hostname: peatio
    extra_hosts:
     - "peatio.freeriding.us:172.18.0.8"
     - "peatio.freeriding.us:167.99.168.129"
    dns:
     - 172.18.0.8
     - 167.99.168.129
    dns_search:
     - peatio.freeriding.us
    volumes:
      - ../config/peatio/seed:/opt/peatio/config/seed
      - ../config/peatio/management_api_v1.yml:/opt/peatio/config/management_api_v1.yml
      - ../config/peatio/plugins.yml:/opt/peatio/config/plugins.yml
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:peatio.${APP_DOMAIN}"
      traefik.port: 8000
    command: bash -c "bin/link_config && bundle exec puma --config config/puma.rb"

  barong:
    image: "${BARONG_IMAGE}"
    env_file:
      - ../config/barong.env
    ports:
      - "167.99.168.129:8001:8001"
    domainname: barong.freeriding.us
    hostname: barong
    extra_hosts:
     - "barong.freeriding.us:172.18.0.7"
     - "barong.freeriding.us:167.99.168.129"
    dns:
     - 172.18.0.7
     - 178.128.2.160
    dns_search:
     - barong.freeriding.us
    volumes:
      - ../config/secrets:/secrets:ro
      - ../config/barong/seeds.yml:/home/app/config/seeds.yml
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:barong.${APP_DOMAIN}"
      traefik.port: 8001
