version: '3.6'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeme

  redis:
    image: redis:4.0.10
    restart: always
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.7.6-management
    restart: always
    ports:
      - "178.128.2.160:15672:15672"     
    domainname: rabbitmq.satoshisoup.com
    hostname: rabbitmq
    extra_hosts:
     - "rabbitmq.satoshisoup.com:172.18.0.4"
     - "rabbitmq.satoshisoup.com:178.128.2.160"
    dns:
     - 172.18.0.4
     - 178.128.2.160
    dns_search:
     - rabbitmq.satoshisoup.com
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: rabbitmq.${APP_DOMAIN}'
      traefik.port: 15672

  vault:
    image: vault:0.10.2
    restart: always
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: changeme
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

volumes:
  db_data:
  rabbitmq_data:
  redis_data:

