version: '3.6'

services:
  geth:
    image: ethereum/client-go:stable
    #restart: always
    command: |
      --syncmode=full
      --rinkeby
      --rpc
      --rpcaddr=178.128.2.160
      --rpcport=8545
      --port=30303
      --rpcapi="db,personal,eth,net,web3"
      --rpccorsdomain="*"
      --rpcvhosts="eth.freeriding.us"
    ports:
     - "167.99.168.129:8545:8545"
    domainname: eth.freeriding.us
    hostname: cryptonodes
    extra_hosts:
     - "eth.freeriding.us:172.18.0.7"
     - "eth.freeriding.us:167.99.168.129"
    dns:
     - 172.18.0.6
     - 167.99.168.129
    dns_search:
     - eth.freeriding.us
    volumes:
      - eth-data:/root/.ethereum/
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: eth.${APP_DOMAIN}'
      traefik.port: 8545

volumes:
  eth-data:
