version: '3.6'

services:
  frontend:
    image: "${FRONTEND_IMAGE}"
    ports:
       - "167.99.168.129:3000:3000"
    domainname: www.freeriding.us
    extra_hosts:
      - "www.freeriding.us:172.18.0.10"
      - "www.freeriding.us:167.99.168.129"
    dns:
      - 172.18.0.10
      - 167.99.168.129
    dns_search:
      - www.freeriding.us
    env_file:
      - ../config/frontend.env      
    volumes:
      - ../config/frontend/frontend.js:/home/node/public/env.js           
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/;Host:www.${APP_DOMAIN}"
      traefik.port: 3000

  tower:
    image: "${TOWER_IMAGE}"
    user: "${UID}:${GID}"
    ports:
      - "167.99.168.129:8080:8080"
    domainname: tower.freeriding.us
    extra_hosts:
      - "tower.www.freeriding.us:172.18.0.11"
      - "tower.www.freeriding.us:167.99.168.129"
    dns:
      - 172.18.0.11
      - 167.99.168.129
    dns_search:
      - tower.www.freeriding.us   
    #command: "-d /home/app/build -s 1"
    volumes:
      #- ../vendor/tower:/home/app
      - ../config/frontend/tower.js:/home/app/env.js      
    labels:
      traefik.enable: true
      traefik.frontend.rule: "PathPrefix:/tower;Host:www.${APP_DOMAIN}"
      traefik.port: 8080
