version: '3.6'

services:
  proxy:
    image: traefik
    ports:
      - "167.99.168.129:80:80"
      - "167.99.168.129:443:443"
    domainname: freeriding.us
    extra_hosts:
     - "freeriding.us:172.18.0.13"
     - "freeriding.us:167.99.168.129"
    dns:
     - 172.18.0.13
     - 167.99.168.129
    dns_search:
     - freeriding.us
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../config/traefik.toml:/etc/traefik/traefik.toml:ro
      - ../config/acme.json:/acme.json
    networks:
      default:
        aliases:
          - www.${APP_DOMAIN}
          - www.app.${APP_DOMAIN}
          - app.www.${APP_DOMAIN}
          - peatio.www.${APP_DOMAIN}
          - barong.www.${APP_DOMAIN}
          - tower.www.${APP_DOMAIN}
          - trading.www.${APP_DOMAIN}    
          - peatio.${APP_DOMAIN}
          - barong.${APP_DOMAIN}
          - ws.ranger.${APP_DOMAIN}
          - mail.${APP_DOMAIN}
          - btc.${APP_DOMAIN}
          - pma.${APP_DOMAIN}
          - eth.${APP_DOMAIN}
          - tower.${APP_DOMAIN}
          - monitor.${APP_DOMAIN}
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: monitor.${APP_DOMAIN}'
      traefik.port: 8080
